server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://10.15.17.127:3306/one_home?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: onehome_2020
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.web: ERROR
    vn.vnpt.stc.enterprise: DEBUG
    org.hibernate.cache.jcache.access.AbstractReadWriteRegionAccessStrategy: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} node=${app.node} service=${app.service} v${app.version} [%thread] %-5level %logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} node=${app.node} service=${app.service} v${app.version} [%thread] %-5level %logger{36} : %msg%n"
  ignoreLog:
    NotificationService: search
xxl:
  job:
    admin:
      addresses: http://localhost:8091/xxl-job-admin
      api: http://localhost:8091/xxl-job-admin
    ### xxl-job, access token
    accessToken: default_token

    ### xxl-job executor appname
    executor:
      appname: system-core-executor
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      ### xxl-job executor server-info
      ip:
      port: 9998
      ### xxl-job executor log-path
      logpath: D:/xxl-job/jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 3
  group:
    cron-id: 2
  delay: 5

